package lintubongari.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import lintubongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.23 10:10:24 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HavainnotTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista53 
   * @throws SailoException when error
   */
  @Test
  public void testPoista53() throws SailoException {    // Havainnot: 53
    Havainnot havainnot = new Havainnot(); 
    Havainto h1 = new Havainto(); Havainto h2 = new Havainto(); Havainto h3 = new Havainto(); 
    h1.rekisteroi(); h2.rekisteroi(); h3.rekisteroi(); 
    int id = h1.getId(); 
    havainnot.lisaa(h1); havainnot.lisaa(h2); havainnot.lisaa(h3); 
    assertEquals("From: Havainnot line: 60", 3, havainnot.getLkm()); 
    havainnot.poista(id); 
    assertEquals("From: Havainnot line: 62", 2, havainnot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta96 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta96() throws SailoException {    // Havainnot: 96
    Havainnot havainnot = new Havainnot(); 
    Havainto h1 = new Havainto(), h2 = new Havainto(); 
    h1.rekisteroi(); h2.rekisteroi(); 
    h1.taytaHavaintoH(); h2.taytaHavaintoH(); 
    String hakemisto = "testi"; 
    String tiedNimi = hakemisto+"/havainnot"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    havainnot.lueTiedostosta(tiedNimi); 
    fail("Havainnot: 110 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    havainnot.lisaa(h1); 
    havainnot.lisaa(h2); 
    havainnot.tallenna(); 
    havainnot = new Havainnot(); 
    havainnot.lueTiedostosta(tiedNimi); 
    assertEquals("From: Havainnot line: 116", true, havainnot.anna(0).toString().equals(h1.toString())); 
    assertEquals("From: Havainnot line: 117", true, havainnot.anna(1).toString().equals(h2.toString())); 
    havainnot.lisaa(h2); 
    havainnot.tallenna(); 
    assertEquals("From: Havainnot line: 120", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Havainnot line: 122", true, fbak.delete()); 
    assertEquals("From: Havainnot line: 123", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnna219 
   * @throws SailoException when error
   */
  @Test
  public void testAnna219() throws SailoException {    // Havainnot: 219
    Havainnot h = new Havainnot(); 
    Havainto h1 = new Havainto(); 
    Havainto h2 = new Havainto(); 
    h.lisaa(h1); h.lisaa(h2); 
    assertEquals("From: Havainnot line: 225", true, h.anna(0).equals(h1)); 
    assertEquals("From: Havainnot line: 226", true, h.anna(1).equals(h2)); 
  } // Generated by ComTest END
}