package lintubongari.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import lintubongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.23 10:11:04 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HavaintotietoTest {



  // Generated by ComTest BEGIN
  /** testGetHavaintoId25 */
  @Test
  public void testGetHavaintoId25() {    // Havaintotieto: 25
    Havaintotieto h1 = new Havaintotieto(); 
    h1.setHavaintoId(3); 
    assertEquals("From: Havaintotieto line: 28", 3, h1.getHavaintoId()); 
  } // Generated by ComTest END
}