package lintubongari.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import lintubongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.23 10:10:40 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HavaintoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi23 */
  @Test
  public void testRekisteroi23() {    // Havainto: 23
    Havainto h1 = new Havainto(); 
    h1.rekisteroi(); 
    Havainto h2 = new Havainto(); 
    h2.rekisteroi(); 
    int n1 = h1.getId(); 
    int n2 = h2.getId(); 
    assertEquals("From: Havainto line: 30", n2-1, n1); 
  } // Generated by ComTest END
}