package lintubongari.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import lintubongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.23 10:11:14 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LajiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi22 */
  @Test
  public void testRekisteroi22() {    // Laji: 22
    Laji l1 = new Laji(); 
    l1.rekisteroi(); 
    Laji l2 = new Laji(); 
    l2.rekisteroi(); 
    int n1 = l1.getId(); 
    int n2 = l2.getId(); 
    assertEquals("From: Laji line: 29", n2-1, n1); 
  } // Generated by ComTest END
}