package lintubongari.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import lintubongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.23 10:11:25 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LajitTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista66 
   * @throws SailoException when error
   */
  @Test
  public void testPoista66() throws SailoException {    // Lajit: 66
    Lajit lajit = new Lajit(); 
    Laji l1 = new Laji(); Laji l2 = new Laji(); Laji l3 = new Laji(); 
    l1.rekisteroi(); l2.rekisteroi(); l3.rekisteroi(); 
    int id = l1.getId(); 
    lajit.lisaa(l1); lajit.lisaa(l2); lajit.lisaa(l3); 
    assertEquals("From: Lajit line: 73", 3, lajit.getLkm()); 
    lajit.poista(id); 
    assertEquals("From: Lajit line: 75", 2, lajit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta93 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta93() throws SailoException {    // Lajit: 93
    Lajit lajit = new Lajit(); 
    Laji l1 = new Laji(), l2 = new Laji(); 
    l1.rekisteroi(); l2.rekisteroi(); 
    l1.taytaLaji(); l2.taytaLaji(); 
    String hakemisto = "testi"; 
    String tiedNimi = hakemisto+"/havainnot"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    lajit.lueTiedostosta(tiedNimi); 
    fail("Lajit: 107 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    lajit.lisaa(l1); 
    lajit.lisaa(l2); 
    lajit.tallenna(); 
    lajit = new Lajit(); 
    lajit.lueTiedostosta(tiedNimi); 
    assertEquals("From: Lajit line: 113", true, lajit.get(0).toString().equals(l1.toString())); 
    assertEquals("From: Lajit line: 114", true, lajit.get(1).toString().equals(l2.toString())); 
    lajit.lisaa(l2); 
    lajit.tallenna(); 
    assertEquals("From: Lajit line: 117", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Lajit line: 119", true, fbak.delete()); 
    assertEquals("From: Lajit line: 120", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna225 */
  @Test
  public void testAnna225() {    // Lajit: 225
    Lajit lajit = new Lajit(); 
    Laji l = new Laji(); 
    l.rekisteroi(); l.taytaLaji(); lajit.lisaa(l); 
    assertEquals("From: Lajit line: 229", true, l.equals(lajit.anna(1))); 
  } // Generated by ComTest END
}