package lintubongari.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import lintubongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.23 10:11:36 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LintubongariTest {



  // Generated by ComTest BEGIN
  /** 
   * testHaeHavainnonTiedot20 
   * @throws SailoException when error
   */
  @Test
  public void testHaeHavainnonTiedot20() throws SailoException {    // Lintubongari: 20
    Lintubongari lintubongari = new Lintubongari(); 
    Havaintotieto ht = new Havaintotieto(); Havaintotieto ht2 = new Havaintotieto(); 
    ht.taytaHavaintotieto(1); ht2.taytaHavaintotieto(2); 
    lintubongari.lisaa(ht); lintubongari.lisaa(ht2); 
    Havaintotieto havainnonTiedot = lintubongari.haeHavainnonTiedot(1); 
    assertEquals("From: Lintubongari line: 28", true, havainnonTiedot.equals(ht)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista120 
   * @throws Exception when error
   */
  @Test
  public void testPoista120() throws Exception {    // Lintubongari: 120
    Lintubongari lb = new Lintubongari(); 
    Havainto h1 = new Havainto(); Havainto h2 = new Havainto(); 
    h1.rekisteroi(); h2.rekisteroi(); 
    Laji l1 = new Laji(); Laji l2 = new Laji(); 
    l1.rekisteroi(); l2.rekisteroi(); 
    Havaintotieto ht1 = new Havaintotieto(); Havaintotieto ht2 = new Havaintotieto(); 
    ht1.taytaHavaintotieto(1); ht2.setLajiId(2); ht2.setHavaintoId(2); 
    lb.lisaa(h1); lb.lisaa(h2); lb.lisaa(l1); lb.lisaa(l2); lb.lisaa(ht1); lb.lisaa(ht2); 
    assertEquals("From: Lintubongari line: 130", 2, lb.getLajeja()); 
    assertEquals("From: Lintubongari line: 131", 2, lb.getHavaintoja()); 
    assertEquals("From: Lintubongari line: 132", 2, lb.getHavaintotietoja()); 
    lb.poista(0); 
    assertEquals("From: Lintubongari line: 134", 1, lb.getLajeja()); 
    assertEquals("From: Lintubongari line: 135", 1, lb.getHavaintoja()); 
    assertEquals("From: Lintubongari line: 136", 1, lb.getHavaintotietoja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostostaHavainnot218 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostostaHavainnot218() throws SailoException {    // Lintubongari: 218
    Lintubongari lintubongari = new Lintubongari(); 
    Havainto h1 = new Havainto(); h1.taytaHavaintoH(); h1.rekisteroi(); 
    Havainto h2 = new Havainto(); h2.taytaHavaintoH(); h2.rekisteroi(); 
    Laji l1 = new Laji(); l1.taytaLaji(); l1.rekisteroi(); 
    Laji l2 = new Laji(); l2.taytaLaji(); l2.rekisteroi(); 
    Havaintotieto ht1 = new Havaintotieto(); 
    Havaintotieto ht2 = new Havaintotieto(); 
    ht1.taytaHavaintotieto(h1.getId()); ht2.taytaHavaintotieto(h2.getId()); 
    String hakemisto = "testi"; 
    File dir = new File(hakemisto); 
    File ftied  = new File(hakemisto+"/havainnot.dat"); 
    File fltied = new File(hakemisto+"/lajit.dat"); 
    File fhttied = new File(hakemisto+"/havaintotiedot.dat"); 
    dir.mkdir(); 
    ftied.delete(); 
    fltied.delete(); 
    fhttied.delete(); 
    try {
    lintubongari.lueTiedostostaHavainnot(hakemisto); 
    fail("Lintubongari: 242 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    lintubongari.lisaa(h1); 
    lintubongari.lisaa(h2); 
    lintubongari.lisaa(l1); 
    lintubongari.lisaa(l2); 
    lintubongari.lisaa(ht1); 
    lintubongari.lisaa(ht2); 
    lintubongari.tallenna(); 
    lintubongari = new Lintubongari(); 
    lintubongari.lueTiedostostaHavainnot(hakemisto); 
    lintubongari.annaHavainto(0).toString().equals(h1.toString()); 
    lintubongari.annaHavaintotieto(0).toString().equals(ht1.toString()); 
    lintubongari.annaHavainto(1).toString().equals(h2.toString()); 
    lintubongari.annaHavaintotieto(1).toString().equals(ht2.toString()); 
    lintubongari.annaLaji(0).toString().equals(l1.toString()); 
    lintubongari.annaLaji(1).toString().equals(l2.toString()); 
    lintubongari.lisaa(l2); 
    lintubongari.lisaa(ht2); 
    lintubongari.lisaa(h2); 
    lintubongari.tallenna(); 
    assertEquals("From: Lintubongari line: 262", true, ftied.delete()); 
    assertEquals("From: Lintubongari line: 263", true, fltied.delete()); 
    assertEquals("From: Lintubongari line: 264", true, fhttied.delete()); 
    File fbak = new File(hakemisto+"/havainnot.bak"); 
    File flbak = new File(hakemisto+"/lajit.bak"); 
    File fhtbak = new File(hakemisto+"/havaintotiedot.bak"); 
    assertEquals("From: Lintubongari line: 268", true, fbak.delete()); 
    assertEquals("From: Lintubongari line: 269", true, flbak.delete()); 
    assertEquals("From: Lintubongari line: 270", true, fhtbak.delete()); 
    assertEquals("From: Lintubongari line: 271", true, dir.delete()); 
  } // Generated by ComTest END
}